[package]
name = "lance"
version = "0.1.0"
authors = ["Karl Bateman <33239151+karlbateman@users.noreply.github.com>"]
edition = "2018"

[dependencies]
num = "0.1.27"
image = "0.13.0"
crossbeam = "0.2.8"
